services:
  db: 
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=rudra123
      - POSTGRES_USER=rudra
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
volumes:
  db-data: